### ISSUE TITLE
Adicionar templates para issues e pull requests

### ISSUE THREAD

**Issue by cantuariavc** [fga-eps-mds/2019.2-Grupo9#2]
**Sua funcionalidade requisitada é relacionada com um problema? Descreva, por favor.**
 
Gostaria de criar issues e templates com facilidade e padronizados.

  **Descreva a solução que você gostaria**
 
Possuir templates para facilitar a criação de issues e de pull requests.

  **Descreva uma alternativa considerada**
 
Seguir os passos mostrados pelo GitHub para criar os templates.

  **Informações adicionais**
 

  **Checklist**  
 - [x] A issue possui nome significativo.
 - [x] A issue possui descrição significativa.
 - [x] A issue possui screenshots quando necessárias.
 - [x] A issue possui labels.

**Comment by MateusO97** [comment]
Resolvido em #1
